# [neste exemplo, o directório com o dataset está dentro do directório com as scripts]
setwd("auto+mpg")

# [carregar as scripts the caracterização dos dados]
source("../gsi.R", chdir = TRUE)

#kCompleteRegressionGSI <- list(name="gsi_complete_regression", version="1.0", target.declared=TRUE, measures=c("n.examples", "log.n.examples", "n.attrs", "n.examples.rel.n.attrs", "log.n.examples.rel.n.attrs", "n.continuous.attrs", "n.symbolic.attrs", "n.binary.attrs", "prop.continuous.attrs", "prop.symbolic.attrs", "prop.binary.attrs", "attr.correlation", "avg.abs.attr.correlation", "min.abs.attr.correlation", "max.abs.attr.correlation", "h.outlier", "n.h.outlier", "prop.h.outlier", "skewness", "avg.skewness", "kurtosis", "avg.kurtosis", "symb.value.freq", "symb.pair.value.freq", "symb.pair.mutual.information", "attr.entropy", "symb.pair.mutual.information", "res.symb.pair.mutual.information", "avg.res.symb.pair.mutual.information", "min.res.symb.pair.mutual.information", "max.res.symb.pair.mutual.information", "target.correlation", "avg.abs.target.correlation", "min.abs.target.correlation", "max.abs.target.correlation", "res.symb.value.target.range", "avg.res.symb.value.target.range", "min.avg.res.symb.value.target.range", "symb.target.fstat.pval", "avg.symb.target.fstat.pval", "min.symb.target.fstat.pval", "max.symb.target.fstat.pval", "target.stationarity", "target.coefficient.variation", "target.cv.sparsity", "target.abscv.sparsity", "target.hist.sparsity", "target.h.outlier", "target.has.outliers", "mean.res.dist.adjacent.target", "avg.mean.res.dist.adjacent.target", "r.squared", "r.squared.bin.symb", "dispersion.gain", "avg.dispersion.gain", "min.dispersion.gain", "max.dispersion.gain"))
#kCompleteRegressionGSI <- list(name="gsi_complete_regression", version="1.0", target.declared=TRUE, measures=c("n.examples", "log.n.examples", "n.attrs", "n.examples.rel.n.attrs", "log.n.examples.rel.n.attrs", "n.continuous.attrs", "n.symbolic.attrs", "n.binary.attrs", "prop.continuous.attrs", "prop.symbolic.attrs", "prop.binary.attrs", "attr.correlation", "avg.abs.attr.correlation", "min.abs.attr.correlation", "max.abs.attr.correlation", "h.outlier", "n.h.outlier", "prop.h.outlier", "skewness", "avg.skewness", "kurtosis", "avg.kurtosis", "symb.value.freq", "symb.pair.value.freq", "symb.pair.mutual.information", "attr.entropy", "symb.pair.mutual.information", "res.symb.pair.mutual.information", "avg.res.symb.pair.mutual.information", "min.res.symb.pair.mutual.information", "max.res.symb.pair.mutual.information", "target.correlation", "avg.abs.target.correlation", "min.abs.target.correlation", "max.abs.target.correlation", "res.symb.value.target.range", "avg.res.symb.value.target.range", "min.avg.res.symb.value.target.range", "symb.target.fstat.pval", "avg.symb.target.fstat.pval", "min.symb.target.fstat.pval", "max.symb.target.fstat.pval", "target.stationarity", "target.coefficient.variation", "abs.target.coefficient.variation", "target.cv.sparsity", "target.abscv.sparsity", "target.hist.sparsity", "target.h.outlier", "target.has.outliers", "mean.res.dist.adjacent.target", "avg.mean.res.dist.adjacent.target", "r.squared", "r.squared.bin.symb", "dispersion.gain", "avg.dispersion.gain", "min.dispersion.gain", "max.dispersion.gain"))  

# [cálculo do sub-conjunto de meta-features chamada "kCompleteClassificationGSI" para o dataset "car", gravando o resultado no ficheiro "car.gsi]
METALCharacterization("auto-mpg-ncont-0nom", "auto-mpg-ncont-0nom.gsi", kCompleteRegressionGSI) # ok
METALCharacterization("auto-mpg-ncont-1nom", "auto-mpg-ncont-1nom.gsi", kCompleteRegressionGSI) # ok
METALCharacterization("auto-mpg-ncont-nnom", "auto-mpg-ncont-nnom.gsi", kCompleteRegressionGSI) # ok
METALCharacterization("auto-mpg-1cont-nnom", "auto-mpg-1cont-nnom.gsi", kCompleteRegressionGSI) # ok
METALCharacterization("auto-mpg-0cont-nnom", "auto-mpg-0cont-nnom.gsi", kCompleteRegressionGSI) # ok


